In [1]:
import pandas as pd
import os
import glob
from pathlib import Path

In [2]:
def cargar_csv():
    """
    Carga los archivos principales de la EPA y los anexos
    desde data/raw y devuelve dos diccionarios:
    - dfs: archivos principales
    - dfs_a: anexos
    """

    ruta = Path("../data/raw")  # carpeta donde están los datos

    dfs = {}    # aquí guardamos los df principales
    dfs_a = {}  # aquí guardamos los df de los anexos

    # Carga de archivos principales

    for file in sorted(ruta.glob("EPA_*")):        
        if "Anexo" in file.stem: # Evitar anexos
            continue
        if file.suffix == ".tab":
            df = pd.read_csv(file, sep="\t", encoding="utf-8", low_memory=False)
        else:
            df = pd.read_csv(file, sep="\t", encoding="utf-8", low_memory=False)
            # esto lo dejamos así porque, aunque la extensión sea distinta,
            # en la práctica también van separados por tabulación

        key = file.stem
        dfs[key] = df

    # Carga de anexos

    for file in sorted(ruta.glob("EPAAnexo_*")):
        if file.suffix == ".tab":
            df = pd.read_csv(file, sep="\t", encoding="utf-8", low_memory=False)
        else:
            df = pd.read_csv(file, encoding="utf-8", low_memory=False)

        key = file.stem
        dfs_a[key] = df

    return dfs, dfs_a

In [3]:
dfs, dfs_a = cargar_csv()

In [4]:
dfs["EPA_2021T1"]

,CICLO,CCAA,PROV,NVIVI,NIVEL,NPERS,EDAD1,RELPP1,SEXO1,NCONY,...,SIDI3,SIDAC1,SIDAC2,DAUSVAC,DAUSENF,DAUSOTR,TRAANT,AOI,RELLB4,FACTOREL
0,194,16,1,1,1,1,40,1,1,2,...,,1,1,2.0,NaN,NaN,1,04,,193.90
1,194,16,1,1,1,2,30,2,6,1,...,,1,1,NaN,NaN,NaN,1,03,,193.90
2,194,16,1,2,1,1,35,1,6,2,...,,1,1,1.0,NaN,NaN,1,04,,252.32
3,194,16,1,2,1,2,30,2,1,1,...,,1,1,1.0,NaN,NaN,1,04,,252.32
4,194,16,1,2,2,3,0,3,6,0,...,,,,NaN,NaN,NaN,,,,252.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142845,194,52,52,57996,1,2,25,3,6,0,...,,1,1,NaN,NaN,NaN,6,04,,155.14
142846,194,52,52,57996,1,3,20,3,6,0,...,,2,2,NaN,NaN,NaN,6,05,,155.14
142847,194,52,52,57997,1,1,30,1,1,2,...,,1,1,NaN,NaN,NaN,1,04,,439.75
142848,194,52,52,57997,1,2,30,2,6,1,...,,1,1,NaN,NaN,NaN,1,04,,439.75
142849,194,52,52,57997,2,3,0,3,1,0,...,,,,NaN,NaN,NaN,,,,439.75

In [5]:
# Crear la carpeta de salida si no existe
ruta_salida = Path("../data/interim")
ruta_salida.mkdir(parents=True, exist_ok=True)

for nombre, df in dfs.items():
    # Hacemos una copia para no tocar el original
    df_nuevo = df.rename(columns={"HORPLU": "HOREPLU"})
    
    # Guardamos el nuevo CSV
    df_nuevo.to_csv(ruta_salida / f"{nombre}.csv", index=False)

A continuación vamos a hacer otra función para cargar los nuevos csv que son los que vamos a mergear.

In [33]:
def cargar_csv_int():

    """
    Cargo los EPA principales desde data/interim,
    porque ahí ya tengo las columnas normalizadas.

    Cargo los EPAAnexo desde data/raw,
    porque los anexos no los he guardado en interim.
    """

    dfs = {}
    dfs_a = {}

    ruta_interim = Path("../data/interim")
    ruta_raw = Path("../data/raw")

    # Cargo EPA principales desde interim
    for file in sorted(ruta_interim.glob("EPA_*.csv")):

        nombre = file.stem

        # Evito cargar archivos finales tipo EPA_joined
        if "joined" in nombre.lower():

            continue

        df = pd.read_csv(
            file,
            low_memory=False
        )

        dfs[nombre] = df

    # Cargo anexos desde raw
    for file in sorted(ruta_raw.glob("EPAAnexo_*.tab")):

        df = pd.read_csv(
            file,
            sep="\t",
            encoding="latin1",
            low_memory=False
        )

        nombre = file.stem

        dfs_a[nombre] = df

    return dfs, dfs_a

In [34]:
dfs, dfs_a = cargar_csv_int()

In [35]:
print("EPA principales:")
print(list(dfs.keys())[:10])

print("Anexos:")
print(list(dfs_a.keys())[:10])

print("Número EPA:", len(dfs))
print("Número anexos:", len(dfs_a))

EPA principales:
['EPA_2021T1', 'EPA_2021T2', 'EPA_2021T3', 'EPA_2021T4', 'EPA_2022T1', 'EPA_2022T2', 'EPA_2022T3', 'EPA_2022T4', 'EPA_2023T1', 'EPA_2023T2']
Anexos:
['EPAAnexo_2021T1', 'EPAAnexo_2021T2', 'EPAAnexo_2021T3', 'EPAAnexo_2021T4', 'EPAAnexo_2022T1', 'EPAAnexo_2022T2', 'EPAAnexo_2022T3', 'EPAAnexo_2022T4', 'EPAAnexo_2023T1', 'EPAAnexo_2023T2']
Número EPA: 20
Número anexos: 12

In [40]:
CLAVES = ["CICLO", "CCAA", "NVIVI", "NIVEL", "NPERS"]


def mergear_epa_con_anexo(dfs, dfs_a):

    dfs_mergeados = {}

    for nombre_epa, df_epa in dfs.items():

        periodo = nombre_epa.replace("EPA_", "")
        nombre_anexo = f"EPAAnexo_{periodo}"

        # Si no hay anexo, dejo el EPA tal cual
        if nombre_anexo not in dfs_a:

            dfs_mergeados[nombre_epa] = df_epa.copy()
            print(f"{nombre_epa} sin anexo")

            continue

        df_anexo = dfs_a[nombre_anexo]

        # Busco la columna del peso
        columnas_fac = [
            col for col in df_anexo.columns
            if col.startswith("FACB")
        ]

        columna_fac = columnas_fac[0]

        # Me quedo solo con claves + peso
        df_anexo_reducido = df_anexo[
            CLAVES + [columna_fac]
        ].copy()

        # Uno EPA + anexo
        df_mergeado = df_epa.merge(
            df_anexo_reducido,
            on=CLAVES,
            how="left",
            validate="one_to_one"
        )

        # Creo una columna común
        df_mergeado["PESO"] = df_mergeado[columna_fac]

        dfs_mergeados[nombre_epa] = df_mergeado

        print(f"{nombre_epa} mergeado | peso: {columna_fac}")

    return dfs_mergeados

In [41]:
dfs_mergeados = mergear_epa_con_anexo(dfs, dfs_a)

EPA_2021T1 mergeado | peso: FACB2021
EPA_2021T2 mergeado | peso: FACB2021
EPA_2021T3 mergeado | peso: FACB2021
EPA_2021T4 mergeado | peso: FACB2021
EPA_2022T1 mergeado | peso: FACB2021
EPA_2022T2 mergeado | peso: FACB2021
EPA_2022T3 mergeado | peso: FACB2021
EPA_2022T4 mergeado | peso: FACB2021
EPA_2023T1 mergeado | peso: FACB2021
EPA_2023T2 mergeado | peso: FACB2021
EPA_2023T3 mergeado | peso: FACB2021
EPA_2023T4 mergeado | peso: FACB2021
EPA_2024T1 sin anexo
EPA_2024T2 sin anexo
EPA_2024T3 sin anexo
EPA_2024T4 sin anexo
EPA_2025T1 sin anexo
EPA_2025T2 sin anexo
EPA_2025T3 sin anexo
EPA_2025T4 sin anexo

In [42]:
ruta_salida = Path("../data/interim/epa_mergeada")
ruta_salida.mkdir(parents=True, exist_ok=True)

for nombre, df in dfs_mergeados.items():

    archivo_salida = ruta_salida / f"{nombre}_mergeado.csv"

    df.to_csv(
        archivo_salida,
        index=False
    )

    print(f"Guardado: {archivo_salida}")

Guardado: ../data/interim/epa_mergeada/EPA_2021T1_mergeado.csv
Guardado: ../data/interim/epa_mergeada/EPA_2021T2_mergeado.csv
Guardado: ../data/interim/epa_mergeada/EPA_2021T3_mergeado.csv
Guardado: ../data/interim/epa_mergeada/EPA_2021T4_mergeado.csv
Guardado: ../data/interim/epa_mergeada/EPA_2022T1_mergeado.csv
Guardado: ../data/interim/epa_mergeada/EPA_2022T2_mergeado.csv
Guardado: ../data/interim/epa_mergeada/EPA_2022T3_mergeado.csv
Guardado: ../data/interim/epa_mergeada/EPA_2022T4_mergeado.csv
Guardado: ../data/interim/epa_mergeada/EPA_2023T1_mergeado.csv
Guardado: ../data/interim/epa_mergeada/EPA_2023T2_mergeado.csv
Guardado: ../data/interim/epa_mergeada/EPA_2023T3_mergeado.csv
Guardado: ../data/interim/epa_mergeada/EPA_2023T4_mergeado.csv
Guardado: ../data/interim/epa_mergeada/EPA_2024T1_mergeado.csv
Guardado: ../data/interim/epa_mergeada/EPA_2024T2_mergeado.csv
Guardado: ../data/interim/epa_mergeada/EPA_2024T3_mergeado.csv
Guardado: ../data/interim/epa_mergeada/EPA_2024T4_mergeado.csv
Guardado: ../data/interim/epa_mergeada/EPA_2025T1_mergeado.csv
Guardado: ../data/interim/epa_mergeada/EPA_2025T2_mergeado.csv
Guardado: ../data/interim/epa_mergeada/EPA_2025T3_mergeado.csv
Guardado: ../data/interim/epa_mergeada/EPA_2025T4_mergeado.csv

Aquí comprobamos, de nuevo, que todas las columnas se llaman igual

In [43]:
lista_columnas = []
for e in dfs.values():
    c= set(e.columns)
    lista_columnas.append(c)

i = 0
ref = lista_columnas[0]

for c in lista_columnas:
    i +=1
    if c == lista_columnas[0]:
        print(f"El grupo {i} es igual, todo bien.")
    else:
        faltan = ref - c
        sobran = c - ref
        print(f"En el grupo{i} faltan estas columnas: \n{faltan}\n y sobran estas columnas \n{sobran}\n")

El grupo 1 es igual, todo bien.
El grupo 2 es igual, todo bien.
El grupo 3 es igual, todo bien.
El grupo 4 es igual, todo bien.
El grupo 5 es igual, todo bien.
El grupo 6 es igual, todo bien.
El grupo 7 es igual, todo bien.
El grupo 8 es igual, todo bien.
El grupo 9 es igual, todo bien.
El grupo 10 es igual, todo bien.
El grupo 11 es igual, todo bien.
El grupo 12 es igual, todo bien.
El grupo 13 es igual, todo bien.
El grupo 14 es igual, todo bien.
El grupo 15 es igual, todo bien.
El grupo 16 es igual, todo bien.
El grupo 17 es igual, todo bien.
El grupo 18 es igual, todo bien.
El grupo 19 es igual, todo bien.
El grupo 20 es igual, todo bien.

In [44]:
# Junto todos los dataframes mergeados
df_final = pd.concat(
    dfs_mergeados.values(),
    ignore_index=True
)

# Ruta de salida
ruta_salida = Path("../data/interim")
ruta_salida.mkdir(parents=True, exist_ok=True)

# Guardar archivo final
archivo_final = ruta_salida / "EPA_joined.csv"
df_final.to_csv(
    archivo_final,
    index=False
)

print("Archivo guardado en:", archivo_final)
print("Dimensiones finales:", df_final.shape)

Archivo guardado en: ../data/interim/EPA_joined.csv
Dimensiones finales: (2516028, 93)

In [46]:
# Comprobación
df_epa_joined = pd.read_csv(archivo_final)

print("Archivo guardado en:", archivo_final)
print("Dimensiones finales:", df_epa_joined.shape)
print("Número de columnas:", len(df_epa_joined.columns))
print("¿Está HOREPLU?", "HOREPLU" in df_epa_joined.columns)
print("¿Sigue HORPLU?", "HORPLU" in df_epa_joined.columns)

/var/folders/18/2jngcg0x5csd3tyb3xj47rrm0000gn/T/ipykernel_55792/1542048693.py:2: DtypeWarning: Columns (12,13,14,15,17,20,22,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,75,76,77,78,79,80,81,82,83,87,88,89) have mixed types. Specify dtype option on import or set low_memory=False.
  df_epa_joined = pd.read_csv(archivo_final)

Archivo guardado en: ../data/interim/EPA_joined.csv
Dimensiones finales: (2516028, 93)
Número de columnas: 93
¿Está HOREPLU? True
¿Sigue HORPLU? False

In [47]:
df_epa_joined.head()

,CICLO,CCAA,PROV,NVIVI,NIVEL,NPERS,EDAD1,RELPP1,SEXO1,NCONY,...,SIDAC2,DAUSVAC,DAUSENF,DAUSOTR,TRAANT,AOI,RELLB4,FACTOREL,FACB2021,PESO
0,194,16,1,1,1,1,40,1,1,2,...,1,2.0,NaN,NaN,1,04,,193.90,174.32,174.32
1,194,16,1,1,1,2,30,2,6,1,...,1,NaN,NaN,NaN,1,03,,193.90,174.32,174.32
2,194,16,1,2,1,1,35,1,6,2,...,1,1.0,NaN,NaN,1,04,,252.32,225.37,225.37
3,194,16,1,2,1,2,30,2,1,1,...,1,1.0,NaN,NaN,1,04,,252.32,225.37,225.37
4,194,16,1,2,2,3,0,3,6,0,...,,NaN,NaN,NaN,,,,252.32,225.37,225.37

In [48]:
df_epa_joined.sample(10)

,CICLO,CCAA,PROV,NVIVI,NIVEL,NPERS,EDAD1,RELPP1,SEXO1,NCONY,...,SIDAC2,DAUSVAC,DAUSENF,DAUSOTR,TRAANT,AOI,RELLB4,FACTOREL,FACB2021,PESO
2145874,210,5,38,37863,1,3,65,6,6,2,...,NaN,NaN,NaN,NaN,6.0,9.0,NaN,336.73,NaN,NaN
659628,198,8,45,47160,2,4,5,3,6,0,...,,NaN,NaN,NaN,,,,205.12,197.08,197.08
2249769,211,15,31,30273,1,1,55,1,6,0,...,1.0,NaN,NaN,NaN,NaN,4.0,NaN,309.16,NaN,NaN
1356492,204,12,15,13704,1,1,65,1,6,0,...,NaN,NaN,NaN,NaN,NaN,9.0,NaN,220.40,220.40,220.40
859013,200,7,24,21375,1,2,55,2,1,3,...,1,NaN,NaN,NaN,,04,,184.60,157.78,157.78
37356,194,12,15,14955,1,2,35,2,6,1,...,1,NaN,NaN,NaN,1,04,,137.68,134.65,134.65
1516266,205,14,30,28683,1,2,60,2,1,1,...,1.0,NaN,NaN,NaN,NaN,4.0,NaN,331.61,331.61,331.61
1600080,206,8,13,12556,2,2,5,3,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,172.19,NaN,NaN
1287786,203,12,36,38458,1,4,20,3,6,0,...,1.0,1.0,NaN,NaN,NaN,3.0,NaN,342.32,342.32,342.32
765881,199,12,36,36963,1,2,55,2,6,1,...,1,NaN,NaN,NaN,,04,,237.36,228.31,228.31

In [49]:
df_epa_joined.tail()

,CICLO,CCAA,PROV,NVIVI,NIVEL,NPERS,EDAD1,RELPP1,SEXO1,NCONY,...,SIDAC2,DAUSVAC,DAUSENF,DAUSOTR,TRAANT,AOI,RELLB4,FACTOREL,FACB2021,PESO
2516023,213,52,52,45198,1,2,65,2,1,1,...,NaN,NaN,NaN,NaN,NaN,9.0,NaN,65.17,NaN,NaN
2516024,213,52,52,45199,1,1,30,1,1,0,...,1.0,5.0,NaN,NaN,NaN,4.0,NaN,451.33,NaN,NaN
2516025,213,52,52,45200,1,1,65,1,1,0,...,NaN,NaN,NaN,NaN,NaN,9.0,NaN,154.66,NaN,NaN
2516026,213,52,52,45201,1,1,65,1,6,2,...,NaN,NaN,NaN,NaN,NaN,9.0,NaN,96.23,NaN,NaN
2516027,213,52,52,45201,1,2,65,2,1,1,...,NaN,NaN,NaN,NaN,NaN,9.0,NaN,96.23,NaN,NaN

In [50]:
len(df_epa_joined["CICLO"].unique())

20

In [51]:
display(df_epa_joined.describe)

<bound method NDFrame.describe of          CICLO  CCAA  PROV  NVIVI  NIVEL  NPERS  EDAD1  RELPP1  SEXO1  NCONY  \
0          194    16     1      1      1      1     40       1      1      2
1          194    16     1      1      1      2     30       2      6      1
2          194    16     1      2      1      1     35       1      6      2
3          194    16     1      2      1      2     30       2      1      1
4          194    16     1      2      2      3      0       3      6      0
...        ...   ...   ...    ...    ...    ...    ...     ...    ...    ...
2516023    213    52    52  45198      1      2     65       2      1      1
2516024    213    52    52  45199      1      1     30       1      1      0
2516025    213    52    52  45200      1      1     65       1      1      0
2516026    213    52    52  45201      1      1     65       1      6      2
2516027    213    52    52  45201      1      2     65       2      1      1

         ...  SIDAC2  DAUSVAC DAUSENF DAUSOTR TRAANT  AOI  RELLB4 FACTOREL  \
0        ...       1      2.0     NaN     NaN      1   04           193.90
1        ...       1      NaN     NaN     NaN      1   03           193.90
2        ...       1      1.0     NaN     NaN      1   04           252.32
3        ...       1      1.0     NaN     NaN      1   04           252.32
4        ...              NaN     NaN     NaN                       252.32
...      ...     ...      ...     ...     ...    ...  ...     ...      ...
2516023  ...     NaN      NaN     NaN     NaN    NaN  9.0     NaN    65.17
2516024  ...     1.0      5.0     NaN     NaN    NaN  4.0     NaN   451.33
2516025  ...     NaN      NaN     NaN     NaN    NaN  9.0     NaN   154.66
2516026  ...     NaN      NaN     NaN     NaN    NaN  9.0     NaN    96.23
2516027  ...     NaN      NaN     NaN     NaN    NaN  9.0     NaN    96.23

         FACB2021    PESO
0          174.32  174.32
1          174.32  174.32
2          225.37  225.37
3          225.37  225.37
4          225.37  225.37
...           ...     ...
2516023       NaN     NaN
2516024       NaN     NaN
2516025       NaN     NaN
2516026       NaN     NaN
2516027       NaN     NaN

[2516028 rows x 93 columns]>

In [46]:
df_epa_joined["RELLB1"].notnull

<bound method Series.notnull of 0
1
2
3
4
          ...
2516023    NaN
2516024    NaN
2516025    NaN
2516026    NaN
2516027    NaN
Name: RELLB1, Length: 2516028, dtype: object>